version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  
  MyWebApi:
    image: bookstore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7072:7070
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7070
    depends_on:
      - mongo